/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--color-primary), 0.05)',
          100: 'rgb(var(--color-primary), 0.1)',
          200: 'rgb(var(--color-primary), 0.2)',
          300: 'rgb(var(--color-primary), 0.3)',
          400: 'rgb(var(--color-primary), 0.4)',
          500: 'rgb(var(--color-primary), 0.5)',
          600: 'rgb(var(--color-primary), 0.6)',
          700: 'rgb(var(--color-primary), 0.7)',
          800: 'rgb(var(--color-primary), 0.8)',
          900: 'rgb(var(--color-primary), 0.9)',
        },
        secondary: {
          50: 'rgb(var(--color-secondary), 0.05)',
          100: 'rgb(var(--color-secondary), 0.1)',
          200: 'rgb(var(--color-secondary), 0.2)',
          300: 'rgb(var(--color-secondary), 0.3)',
          400: 'rgb(var(--color-secondary), 0.4)',
          500: 'rgb(var(--color-secondary), 0.5)',
          600: 'rgb(var(--color-secondary), 0.6)',
          700: 'rgb(var(--color-secondary), 0.7)',
          800: 'rgb(var(--color-secondary), 0.8)',
          900: 'rgb(var(--color-secondary), 0.9)',
        },
        accent: {
          50: 'rgb(var(--color-accent), 0.05)',
          100: 'rgb(var(--color-accent), 0.1)',
          200: 'rgb(var(--color-accent), 0.2)',
          300: 'rgb(var(--color-accent), 0.3)',
          400: 'rgb(var(--color-accent), 0.4)',
          500: 'rgb(var(--color-accent), 0.5)',
          600: 'rgb(var(--color-accent), 0.6)',
          700: 'rgb(var(--color-accent), 0.7)',
          800: 'rgb(var(--color-accent), 0.8)',
          900: 'rgb(var(--color-accent), 0.9)',
        },
        success: {
          50: 'rgb(var(--color-success), 0.05)',
          100: 'rgb(var(--color-success), 0.1)',
          200: 'rgb(var(--color-success), 0.2)',
          300: 'rgb(var(--color-success), 0.3)',
          400: 'rgb(var(--color-success), 0.4)',
          500: 'rgb(var(--color-success), 0.5)',
          600: 'rgb(var(--color-success), 0.6)',
          700: 'rgb(var(--color-success), 0.7)',
          800: 'rgb(var(--color-success), 0.8)',
          900: 'rgb(var(--color-success), 0.9)',
        },
        warning: {
          50: 'rgb(var(--color-warning), 0.05)',
          100: 'rgb(var(--color-warning), 0.1)',
          200: 'rgb(var(--color-warning), 0.2)',
          300: 'rgb(var(--color-warning), 0.3)',
          400: 'rgb(var(--color-warning), 0.4)',
          500: 'rgb(var(--color-warning), 0.5)',
          600: 'rgb(var(--color-warning), 0.6)',
          700: 'rgb(var(--color-warning), 0.7)',
          800: 'rgb(var(--color-warning), 0.8)',
          900: 'rgb(var(--color-warning), 0.9)',
        },
        error: {
          50: 'rgb(var(--color-error), 0.05)',
          100: 'rgb(var(--color-error), 0.1)',
          200: 'rgb(var(--color-error), 0.2)',
          300: 'rgb(var(--color-error), 0.3)',
          400: 'rgb(var(--color-error), 0.4)',
          500: 'rgb(var(--color-error), 0.5)',
          600: 'rgb(var(--color-error), 0.6)',
          700: 'rgb(var(--color-error), 0.7)',
          800: 'rgb(var(--color-error), 0.8)',
          900: 'rgb(var(--color-error), 0.9)',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'sound-wave': 'sound-wave 1s infinite ease-in-out',
      },
      keyframes: {
        'sound-wave': {
          '0%, 100%': { transform: 'scaleY(1)' },
          '50%': { transform: 'scaleY(2.5)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
};
